version: "3.8"

services:
  db:
    image: postgres:9.6
    volumes:
      - db-data:/var/lib/postgresql/data
      - type: bind
        source: ./local-config/initdb
        target: /docker-entrypoint-initdb.d
        read_only: true
    environment:
      - POSTGRES_PASSWORD=ofbiz
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  ofbiz:
#    build:
#      context: .
    image: ieugen/ofbiz:11-jdk
#    command: /opt/ofbiz/bin/ofbiz --load-data
    volumes:
      - ./local-config/entityengine.postgres.xml:/opt/ofbiz/config/entityengine.xml:ro
    environment:
       - JAVA_OPTS="-Xmx2048m"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8009:8009"
      - "8080:8080"
      - "8443:8443"

volumes:
  db-data: